name: Deploy
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        env:
          REACT_APP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build
